### ISSUE TITLE
Will the substance type change due to optimization?

### ISSUE THREAD

**Issue by HospitableHost** [mit-gfx/diffmat#11]
This is a valuable work. But I still have a question, if a certain material (such as **metal or wood or fabric**) is optimized, will the optimization result still maintain the characteristics of the **metal or wood or fabric**?

**Comment by Polar1s** [comment]
Hi there! Thanks for the great question.

Basically, the optimization algorithm doesn't have a sense of material type - it only sees the graph structure and translates the graph into a differentiable program. The material type labels are assigned by artists. As the loss function is based on VGG features, you can potentially optimize a wood material against a concrete image and get a concrete material instead. It essentially depends on the expressiveness of the graph.
