### ISSUE TITLE
'sbsrender' failed to generate output textures using the default rendering engine. Switching to CPU (SSE2) 

### ISSUE THREAD

**Issue by dongchen-yang** [mit-gfx/diffmat#12]
Hi I encountered this warning when I am running my script of optimizing the material property. Will this affect my final result? Thanks!

**Comment by Polar1s** [comment]
Hi Dongchen, this warning about the engine switch will not affect the final result. You would get other error messages if it did. We actually prefer the CPU engine to GPU-based ones as it's more efficient to distribute rendering tasks across CPU cores (with `OMP_NUM_THREADS=1`).
