### ISSUE TITLE
FileNotFoundError: Configuration file not found for node type: tile_generator

### ISSUE THREAD

**Issue by 1214710638** [mit-gfx/diffmat#3]
hi, i try some sbs files that i download from substance 3d asset website, and i always encounter this problem. can you take a look for me, thanks
python test_nodes.py sbs\mytest\chamfered_concrete_building.sbs -e -b -g
raise FileNotFoundError(f'Configuration file not found for {mode} type: '
FileNotFoundError: Configuration file not found for node type: tile_generator

**Comment by Polar1s** [comment]
Hi there! Sorry for the late response. What you have here suggests that your material graphs have generator or filter nodes not supported by DiffMat, like the Tile Generator node in your case.

We acknowledged the inability to optimize noise generator nodes with the initial code release. Just earlier today we posted a major update in line with our recent SIGGRAPH 2023 paper, which introduced a number of differentiable noise generator nodes including Tile Generator. You could try rerunning your graphs with the latest DiffMat (some changes in environment will be necessary) and see if that helps.

The discussion on this error has also been added to FAQs for future reference. Thank you for bringing the issue to our attention!
