### ISSUE TITLE
AttributeError: module 'diffmat' has no attribute '__version__'

### ISSUE THREAD

**Issue by HospitableHost** [mit-gfx/diffmat#6]
Thanks for your excellent work. I have some trouble in testing the library.
I run "pip install .", and then run "pip install -e ." and then Exit the cloned repo and verify package integrity with:
cd ..
python -c "import diffmat; print(diffmat.__version__)"
(I haven't installed the AS3D or SAT, but it will not affect this issue.)

But! module 'diffmat' has no attribute '__version__'
![image](https://github.com/mit-gfx/diffmat/assets/44576391/d0d24033-668a-4a8a-9994-89f062f543fc)

**Comment by Polar1s** [comment]
That's a good catch. The error has been fixed with the latest commit [98e58d4](https://github.com/mit-gfx/diffmat/commit/98e58d41eeb8048f654e2c44b14e9feac281b4f2).
