### ISSUE TITLE
Node configuration of generator 'fractal_sum_4' does not exist. Revert to use SAT.

### ISSUE THREAD

**Issue by HospitableHost** [mit-gfx/diffmat#8]
Hey, I have bought the Adobe Substance 3D Designer 2023 in steam, and installed it on my ubuntu 20.04.
After I give the current toolkit-path and run this command "python test_nodes.py sbs/match_v1/ceramic_tiles_green.sbs", it reminds me that : 
![image](https://github.com/mit-gfx/diffmat/assets/44576391/0ff4cf02-d293-4437-9e0a-a57af6936993)

So, What went wrong? Do I need to revert to use SAT?

When I use the option "-e" : "python test_nodes.py sbs/match_v1/ceramic_tiles_green.sbs -e", there is no error! Why 0.0?

**Comment by Polar1s** [comment]
There are two separate things here.

- Using `-e` or not controls whether input noise textures are generated from SAT or from DiffMat's internal implementation. Now that you have AS3D installed, the graph translator will automatically generate noise textures using `sbscooker` and `sbsrender` under the `-e` option so you shouldn't see any error. On the other hand, not using `-e` forces DiffMat to compute noises from the translated graph. This is not 100% realistic as implementing each and every generator node in DiffMat incurs way too much work. Therefore, DiffMat will `"revert to use SAT"` by default when it needs to cover unsupported generator nodes. These `[INFO]` messages do not imply errors and you can safely disregard them.

- The explanation of the actual `KeyError` you're seeing can be found in our FAQ document (see README.md).
